apiVersion: v1
kind: Template
labels:
  template: f8a-github-events-monitor
metadata:
  name: f8a-github-events-monitor
  annotations:
    description: f8a-github-events-monitor
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-github-events-monitor
    name: f8a-github-events-monitor
  spec:
    replicas: ${{REPLICAS}}
    selector:
      service: f8a-github-events-monitor
    template:
      metadata:
        labels:
          service: f8a-github-events-monitor
      spec:
        containers:
        - env:
          - name: DEPLOYMENT_PREFIX
            valueFrom:
              configMapKeyRef:
                name: bayesian-config
                key: deployment-prefix
          - name: WORKER_ADMINISTRATION_REGION
            value: "api"
          - name: AWS_SQS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-access-key-id
          - name: AWS_SQS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: sqs-secret-access-key
          - name: PGBOUNCER_SERVICE_HOST
            value: bayesian-pgbouncer
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: database
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: username
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coreapi-postgres
                key: password
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: worker
                key: github-token
          - name: SLEEP_PERIOD
            value: ${SLEEP_PERIOD}
          - name: WATCH_PACKAGES
            value: ${WATCH_PACKAGES}
          - name: LOGLEVEL
            value: ${LOGLEVEL}
          - name: BACKEND_CLASS
            value: ${BACKEND_CLASS}
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-github-events-monitor
          livenessProbe:
            exec:
              command:
              - "true"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 20
          readinessProbe:
            exec:
              command:
              - "true"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Variable which defines the time between updates (in seconds)
  displayName: Sleep period
  name: SLEEP_PERIOD
  value: "600"

- description: A space-separated list of Golang packages that we want to monitor
  displayName: Go packages to watch
  name: WATCH_PACKAGES
  value: "k8s.io/metrics"

- description: Define level of verbosity
  displayName: Logging verbosity
  name: LOGLEVEL
  value: "INFO"

- description: Backend class name; either "LoggerBackend" or "SelinonBackend"
  displayName: Backend class name
  name: BACKEND_CLASS
  value: "LoggerBackend"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/fabric8-analytics-github-events-monitor"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

